
/* Drop Tables */

--DROP TABLE "BOOK_ANSWER" CASCADE CONSTRAINTS;
--DROP TABLE "FREE_ANSWER" CASCADE CONSTRAINTS;
--DROP TABLE "BOOKLIST" CASCADE CONSTRAINTS;
--DROP TABLE "CATEGORY" CASCADE CONSTRAINTS;
--DROP TABLE "FREEWRITE" CASCADE CONSTRAINTS;
--DROP TABLE "MEMBERS" CASCADE CONSTRAINTS;

/* 현재 사용 가능한 모든테이블 DROP 문  */
--SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables


/* Create Tables */

CREATE TABLE book_answer
(
	-- 댓글번호
	an_num number NOT NULL,
	-- 글번호
	an_writenum number,
	-- 내용
	an_content varchar2(2000),
	-- 작성일
	an_regdate timestamp,
	-- 회원 아이디
	an_id varchar2(20),
	PRIMARY KEY (an_num)
);


CREATE TABLE free_answer
(
	-- 댓글번호
	swer_num number NOT NULL,
	-- 글번호
	swer_writenum number,
	-- 내용
	swer_content varchar2(2000),
	-- 작성일
	swer_regdate timestamp,
	-- 회원 아이디
	swer_id varchar2(20),
	PRIMARY KEY (swer_num)
);


-- 등록한 책 글 목록
CREATE TABLE HD04A.BOOKLIST
(
	-- 글 번호
	BOOK_NUM number NOT NULL,
	-- 회원아이디
	book_sellid varchar2(20),
	-- 책 이름
	BOOK_NAME varchar2(50) NOT NULL,
	-- 책 가격
	BOOK_PRICE number NOT NULL,
	-- 작성한 날짜
	BOOK_REGDATE timestamp NOT NULL,
	-- 글 내용
	BOOK_CONTENT clob,
	-- 조회수
	BOOK_VIEWCNT number NOT NULL,
	-- 글 주소
	BOOK_URI varchar2(20) NOT NULL,
	-- 책 카테고리
	BOOK_CATE number NOT NULL,
	-- 이미지 경로
	BOOK_IMAGE varchar2(50),
	-- 판매여부
	BOOK_STATUS char(1) NOT NULL,
	CONSTRAINT BOOKLIST_PK PRIMARY KEY (BOOK_NUM)
);


-- 책 카테고리
CREATE TABLE HD04A.CATEGORY
(
	-- 카테고리 고유번호
	CATE_NUM number NOT NULL,
	-- 카테고리 이름
	CATE_NAME varchar2(20) NOT NULL,
	-- 상위 카테고리
	CATE_PRE varchar2(20) NOT NULL,
	CONSTRAINT CATEGORY_PK PRIMARY KEY (CATE_NUM)
);


CREATE TABLE HD04A.FREEWRITE
(
	FREE_NUM number NOT NULL,
	-- 회원아이디
	free_id number,
	FREE_NAME varchar2(40) NOT NULL,
	FREE_CONTENT clob,
	FREE_VIEWCNT number NOT NULL,
	CONSTRAINT FREEWRITE_PK PRIMARY KEY (FREE_NUM)
);


-- 회원정보
CREATE TABLE HD04A.MEMBERS
(
	mem_num number NOT NULL,
	-- 회원아이디
	MEM_USERID varchar2(20) NOT NULL,
	-- 회원이메일
	MEM_EMAIL varchar2(50) NOT NULL,
	-- 회원 비밀번호
	MEM_PASSWORD varchar2(20) NOT NULL,
	-- 회원 실명
	MEM_USERNAME varchar2(30) NOT NULL,
	-- 연락처
	MEM_PHONE varchar2(14),
	-- 우편번호
	MEM_ZIPCODE varchar2(20),
	-- 집주소1
	MEM_ADDRESS1 varchar2(200),
	-- 집주소2
	MEM_ADDRESS2 varchar2(200),
	-- 회원 등록일
	MEM_REGISTER_DATETIME timestamp NOT NULL,
	-- 가입 상태
	MEM_STATUS char(1) NOT NULL,
	-- 회원 이미지 경로
	MEM_IMAGE varchar2(50),
	CONSTRAINT MEMBERS_PK PRIMARY KEY (mem_num)
);



/* Create Foreign Keys */

ALTER TABLE book_answer
	ADD FOREIGN KEY (an_writenum)
	REFERENCES HD04A.BOOKLIST (BOOK_NUM)
;


ALTER TABLE HD04A.BOOKLIST
	ADD FOREIGN KEY (BOOK_CATE)
	REFERENCES HD04A.CATEGORY (CATE_NUM)
;


ALTER TABLE free_answer
	ADD FOREIGN KEY (swer_writenum)
	REFERENCES HD04A.FREEWRITE (FREE_NUM)
;


ALTER TABLE HD04A.FREEWRITE
	ADD FOREIGN KEY (free_id)
	REFERENCES HD04A.MEMBERS (mem_num)
;



/* Comments */

COMMENT ON COLUMN book_answer.an_num IS '댓글번호';
COMMENT ON COLUMN book_answer.an_writenum IS '글번호';
COMMENT ON COLUMN book_answer.an_content IS '내용';
COMMENT ON COLUMN book_answer.an_regdate IS '작성일';
COMMENT ON COLUMN book_answer.an_id IS '회원 아이디';
COMMENT ON COLUMN free_answer.swer_num IS '댓글번호';
COMMENT ON COLUMN free_answer.swer_writenum IS '글번호';
COMMENT ON COLUMN free_answer.swer_content IS '내용';
COMMENT ON COLUMN free_answer.swer_regdate IS '작성일';
COMMENT ON COLUMN free_answer.swer_id IS '회원 아이디';
COMMENT ON TABLE HD04A.BOOKLIST IS '등록한 책 글 목록';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_NUM IS '글 번호';
COMMENT ON COLUMN HD04A.BOOKLIST.book_sellid IS '회원아이디';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_NAME IS '책 이름';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_PRICE IS '책 가격';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_REGDATE IS '작성한 날짜';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_CONTENT IS '글 내용';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_VIEWCNT IS '조회수';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_URI IS '글 주소';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_CATE IS '책 카테고리';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_IMAGE IS '이미지 경로';
COMMENT ON COLUMN HD04A.BOOKLIST.BOOK_STATUS IS '판매여부';
COMMENT ON TABLE HD04A.CATEGORY IS '책 카테고리';
COMMENT ON COLUMN HD04A.CATEGORY.CATE_NUM IS '카테고리 고유번호';
COMMENT ON COLUMN HD04A.CATEGORY.CATE_NAME IS '카테고리 이름';
COMMENT ON COLUMN HD04A.CATEGORY.CATE_PRE IS '상위 카테고리';
COMMENT ON COLUMN HD04A.FREEWRITE.free_id IS '회원아이디';
COMMENT ON TABLE HD04A.MEMBERS IS '회원정보';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_USERID IS '회원아이디';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_EMAIL IS '회원이메일';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_PASSWORD IS '회원 비밀번호';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_USERNAME IS '회원 실명';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_PHONE IS '연락처';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_ZIPCODE IS '우편번호';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_ADDRESS1 IS '집주소1';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_ADDRESS2 IS '집주소2';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_REGISTER_DATETIME IS '회원 등록일';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_STATUS IS '가입 상태';
COMMENT ON COLUMN HD04A.MEMBERS.MEM_IMAGE IS '회원 이미지 경로';



